// A movie in a local theater is in great demand. To help a local charity, the theater owner has
// decided to donate to the charity a portion of the total amount generated from the movie. Write a
// c++ program that prompts the user to input the
// 1. Movie name
// 2. Adult ticket price
// 3. Child ticket price
// 4. The number of adult tickets sold.
// 5. The number of child tickets sold.
// 6. Percentage of the amount to be donated to the charity.
// First of all, you have to Calculate the total amount generated by the total sold tickets. Then after
// donating to the charity from the total amount, show the remaining amount achieved from the
// movie on the Screen.



#include<iostream>
using namespace std;

main(){
string name;
int ticket1;
int ticket2;
int adult;
int child;
int percentage;
int total;
float charity;
int remaining;

cout<<"Enter the name of movie: ";
cin>>name;
cout<<endl;

cout<<"Enter the adult ticket price: ";
cin>>ticket1;
cout<<endl;

cout<<"Enter the child ticket price: ";
cin>>ticket2;
cout<<endl;

cout<<"Enter the number of adult ticket sold: ";
cin>>adult;
cout<<endl;

cout<<"Enter the number of child ticket sold: ";
cin>>child;
cout<<endl;

cout<<"Enter the percentage of the amount to be donated to charity: ";
cin>>percentage;
cout<<endl;

total=(ticket1*adult)+(ticket2*child);

cout<<"Movie: "<<name<<endl;

cout<<"total amout generated"<<total<<endl;

charity=total*.10;

cout<<"Donation: "<<charity<<endl;

remaining=total-charity;
cout<<"Remaining amount after donation: "<<remaining;
}



